### ISSUE TITLE
The Scripts?

### ISSUE THREAD

**Issue by FiveWinGaming** [mixandjam/GodofWar-AxeThrow#1]
I'm new to unity and found this very cool to look at, i downloaded it and put it into unity but i could not play it because it said the scripts were invalid and they could not be loaded. Any chance you could help me?

**Comment by SongToSoft** [comment]
@FiveWinGaming Hi, now you are resolve this trouble? What version Unity are you using?

**Comment by mixandjam** [comment]
Hey @FiveWinGaming! In order to make sure your project works properly I recommend that you use the same version of Unity as the project was built in (2018.3.5f1)!
Hope it helps! Cheers!
